# Generated by Django 5.2.2 on 2025-06-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpractooos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
    ]
