# Generated by Django 5.2.2 on 2025-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpractooos', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
